### ISSUE TITLE
Uncaught TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by exdeniz** [averrin/color-tabs-regex#1]
[Enter steps to reproduce below:]
1. Add to cson -  "js": "#333" 
2. run atom

**Atom Version**: 1.0.0
**System**: Mac OS X 10.9.5
**Thrown From**: [color-tabs-regex](https://github.com/averrin/color-tabs-regex) package, v0.1.1
### Stack Trace

Uncaught TypeError: Cannot read property 'match' of undefined

```
At /Users/exdeniz/.atom/packages/color-tabs-regex/lib/color-tabs-regex.coffee:41

TypeError: Cannot read property 'match' of undefined
  at Object.<anonymous> (/Users/exdeniz/.atom/packages/color-tabs-regex/lib/color-tabs-regex.coffee:41:18)
  at Object.module.exports.ColorTabsRegex.processAllTabs (/Users/exdeniz/.atom/packages/color-tabs-regex/lib/color-tabs-regex.coffee:81:16)
  at /Users/exdeniz/.atom/packages/color-tabs-regex/lib/color-tabs-regex.coffee:27:23
  at parseContents (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:119:7)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:200:24
  at FSReqWrap.oncomplete (fs.js:77:15)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "jquery-snippets"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-material-syntax, v0.1.2
atom-material-ui, v0.4.15
autocomplete-paths, v1.0.2
color-tabs, v0.1.3
color-tabs-regex, v0.1.1
file-icons, v1.5.8
javascript-snippets, v1.0.0
language-babel, v0.8.1
language-jade, v0.4.0
linter, v1.1.0
linter-eslint, v1.0.11
linter-jscs, v1.12.0
linter-stylint, v2.0.0
navigate-indent, v0.1.0
project-manager, v1.15.10
react, v0.12.3
resize-indent, v0.2.1
tabs-to-spaces, v0.11.0
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by averrin** [comment]
I hope new version fix it. Please update.
So, i add "Edit rules command", you can edit config from atom. Changes will be applied on save

**Comment by exdeniz** [comment]
thanks. Work fine
