### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: /*.js/: Nothing to repeat

### ISSUE THREAD

**Issue by serapath** [averrin/color-tabs-regex#2]
[Enter steps to reproduce below:]
1.  configure `~/.atom/color-tabs-regex.cson

``` cson
"*.js": "#ff0000"
"*.html": "#00ff00"
"*.md": "#0000ff"
"*.markdown": "#0000ff"
"*.html": "#ff00ff"
"*.css": "#00ffff"
"*.json": "#ffff00"
```
1. open `$> atom .`

**Atom Version**: 1.0.0
**System**: Linux Mint
**Thrown From**: [color-tabs-regex](https://github.com/averrin/color-tabs-regex) package, v0.1.2
### Stack Trace

Uncaught SyntaxError: Invalid regular expression: /*.js/: Nothing to repeat

```
At /home/serapath/.atom/packages/color-tabs-regex/lib/color-tabs-regex.coffee:50

SyntaxError: Invalid regular expression: /*.js/: Nothing to repeat
  at new RegExp (native)
  at String.match (native)
  at /home/serapath/.atom/packages/color-tabs-regex/lib/color-tabs-regex.coffee:50:25
  at /home/serapath/.atom/packages/color-tabs-regex/lib/color-tabs-regex.coffee:99:21
  at parseContents (/usr/share/atom/resources/app.asar/node_modules/season/lib/cson.js:119:7)
  at /usr/share/atom/resources/app.asar/node_modules/season/lib/cson.js:200:24
  at FSReqWrap.oncomplete (fs.js:77:15)

```
### Commands

```
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
color-tabs, v0.1.4
color-tabs-regex, v0.1.2
foldername-tabs, v0.1.3
seti-icons, v0.3.0

# Dev
No dev packages
```

**Comment by averrin** [comment]
Due to package storing regex in cson file, it should be escaped. Please try something like '\.js'. It uses string.match function and you can specify onle substring.

**Comment by averrin** [comment]
And i will handle this error in code in couple of days.

**Comment by serapath** [comment]
thx :+1:
